/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package game;

import java.util.ArrayList;
import java.util.Scanner; 
import java.util.Random;


public class App {
    public static void main(String[] args) {
        ArrayList<Game> players = new ArrayList<Game>();
        
        Scanner scanner = new Scanner(System.in);
        System.out.println("---- Game Start ----");
        System.out.println("Player 1 - Enter your name: ");
        String player1Name = scanner.nextLine();
        System.out.println("Player 2 - Enter your name: ");
        String player2Name = scanner.nextLine();
        System.out.println("-----------------------------");

        //randomize who starts
        WordChooser wordChooser = new WordChooser();
        Masker masker = new Masker();
        Game player1 = new Game(wordChooser, masker, player1Name);
        Game player2 = new Game(wordChooser, masker, player2Name);
        players.add(player1);
        players.add(player2);
        Random rand = new Random();
        Integer randomNumber = rand.nextInt(players.size());
        Game first = players.get(randomNumber);
        Game second = players.get(1 - randomNumber);
        
        //how do we avoid they both get the same word?
        System.out.println(first.name + " your word to guess is: " + first.masker.getWordToGuess(first.answer,first.guessedLetters));
        System.out.println(second.name + " your word to guess is: " + second.masker.getWordToGuess(second.answer,second.guessedLetters));
        
        while ( !first.endGame && !second.endGame ) {
            System.out.println("-----------------------------");
            System.out.println(first.name + " you have " + first.getRemainingAttempts().toString() + " lives left. Enter your guess:");
            Character firstInput = scanner.nextLine().charAt(0);
            first.guessLetter(firstInput);
            System.out.println(first.masker.getWordToGuess(first.answer, first.guessedLetters));
            if (first.isGameLost() || first.isGameWon(first.masker.getWordToGuess(first.answer, player1.guessedLetters))) {
                break;
            }
            System.out.println("-----------------------------");
            System.out.println(second.name + " you have " + second.getRemainingAttempts().toString() + " lives left. Enter your guess:");
            Character secondInput = scanner.nextLine().charAt(0);
            second.guessLetter(secondInput);
            System.out.println(second.masker.getWordToGuess(second.answer, second.guessedLetters));
            second.isGameLost();
            second.isGameWon(second.masker.getWordToGuess(second.answer, second.guessedLetters));
          }
        if(first.endGame) {
            System.out.println(first.name + " has won!!");
        } else {
            System.out.println(second.name + " has won!!");
        }
        
    }
}
